[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

norecursedirs =
    .git
    .venv
    .venv-test
    __pycache__
    storage
    uploads
    dist
    node_modules